#!/bin/bash

readonly PF_RULE_FILENAME='pf.conf'
readonly CONFIG_FILENAME='config'
readonly VERSION='0.9.0'

start() {
  sudo pfctl -e
  sudo pfctl -f $PF_RULE_FILENAME
  echo
  echo "banned hosts:"
  while read line; do
    echo $line | grep -v '#' > /dev/null
    if [ $? -eq 0 ]; then
      echo "  $line"
    fi
  done < $CONFIG_FILENAME
  return 0
}

stop() {
  sudo pfctl -d
  return 0
}

usage() {
cat <<EOS
Usage: $0 [-e enable] [-d disable] [-h help] [-v version]
EOS
  return 0
}

version() {
  echo "ban2hst $VERSION"
  return 0
}

main() {
  case $1 in
    "-e")
      start
      ;;
    "-d")
      stop
      ;;
    "-h")
      usage
      ;;
    "-v")
      version
      ;;
    *)
      echo "ban2hst: argument error" 1>&2
      usage
      exit 1
      ;;
  esac
  exit 0 
}

main $@
