#!/bin/bash

readonly NAME='banhst'
readonly ROOT_DIR="`pwd`"
readonly PF_RULE_FILE="$ROOT_DIR/pf.conf"
readonly CONFIG_FILE="$ROOT_DIR/config"
readonly VERSION='0.9.0'

start() {
  # TODO: エラーのハンドリング
  sudo pfctl -e > /dev/null
  sudo pfctl -f $PF_RULE_FILE > /dev/null
  # TODO: ホスト側のIPが変化する可能性があるので定期的にテーブルの更新を行う
  # while true; do sudo pfctl -Tr -t $NAME -f $CONFIG_FILE  > /dev/null; sleep 10; done &
  echo "banned hosts:"
  while read line; do
    echo $line | grep -v '#' > /dev/null
    if [ $? -eq 0 ]; then
      echo "  $line"
    fi
  done < $CONFIG_FILE
  return 0
}

stop() {
  sudo pfctl -d > /dev/null
  return 0
}

usage() {
cat <<EOS
Usage: $0 [-e enable] [-d disable] [-h help] [-v version]
EOS
  return 0
}

version() {
  echo "$NAME $VERSION"
  return 0
}

main() {
  if [ $# -gt 1 ]; then
    echo "$NAME: argument number error" 1>&2
    exit 1
  fi
  case $1 in
    "-e")
      start
      ;;
    "-d")
      stop
      ;;
    "-h")
      usage
      ;;
    "-v")
      version
      ;;
    *)
      echo "$NAME: argument error" 1>&2
      usage
      exit 1
      ;;
  esac
  exit 0 
}

main $@
